name: gctree
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - scons
  - nestly
  - phylip
  - pip
  - pip:
    - . # installs gctree package from current directory "."
